-- AlterTable
ALTER TABLE "User" DROP COLUMN "name",
ADD COLUMN "firstName" TEXT NOT NULL,
ADD COLUMN "lastName" TEXT NOT NULL,
ADD COLUMN "whatsapp" TEXT NOT NULL,
ADD COLUMN "zipCode" TEXT NOT NULL,
ADD COLUMN "state" TEXT NOT NULL,
ADD COLUMN "city" TEXT NOT NULL;